Implement path matching logic for HTML injection
halo-sigs/plugin-injection pull request #11
Opened 2024-08-20 07:44 UTC by CaiHaosen

#### What type of PR is this?
/kind feature
#### What this PR does / why we need it:
此 PR 增加路径匹配逻辑，用户访问特定的页面时，检测到匹配该页面路径的所有启用的代码片段，完成注入
#### Which issue(s) this PR fixes:
Fixes #10 
#### Does this PR introduce a user-facing change?
```release-note
None
```

2024-08-21 07:02 UTC, guqing requested changes

2024-08-21 07:02 UTC, guqing commented on src/main/java/run/halo/injection/AbstractHtmlProcessor.java
> +    private final PathPatternRouteMatcher routeMatcher = new PathPatternRouteMatcher();
默认构造函数中的 PathOptions 值是 `PathContainer.Options.MESSAGE_ROUTE`，这里建议使用 new PathPatternRouteMatcher(PathPatternParser.defaultInstance()) 或者 
```
private final RouteMatcher routeMatcher = createRouteMatcher();

RouteMatcher createRouteMatcher() {
    var parser = new PathPatternParser();
    parser.setPathOptions(PathContainer.Options.HTTP_PATH);
    return new PathPatternRouteMatcher(parser);
}
```

2024-08-21 07:02 UTC, guqing commented on src/main/java/run/halo/injection/HtmlFooterProcessor.java
> +                    && isContentTemplate(context)) {
这里是因为什么需要判断是否为文章或自定义页面的模板呢

2024-08-21 07:02 UTC, guqing commented on ui/src/views/HtmlInjectionAdd.vue
>                  <FormKit type="text" :index="index" help="用于匹配页面路径的正则表达式，如：/archives/**"/>
```suggestion
                <FormKit type="text" :index="index" help="用于匹配页面路径的符合 Ant-style 的表达式，如：/archives/**"/>
```

2024-08-21 07:02 UTC, guqing commented on ui/src/views/HtmlInjectionAdd.vue
>                  <FormKit type="text" :index="index" help="用于匹配页面路径的正则表达式，如：/archives/**"/>
这里的规则被 PathPatternMatcher 使用，它并不是正则表达式的规则

2024-08-21 08:03 UTC, CaiHaosen commented on src/main/java/run/halo/injection/HtmlFooterProcessor.java
> +                    && isContentTemplate(context)) {
如果没有这个判断的话，用户可以在非文章页面注入代码，比如设定路径为/**。所以我加了一个isContentTemplate(context)的判断

2024-08-21 08:06 UTC, guqing commented on src/main/java/run/halo/injection/HtmlFooterProcessor.java
> +                    && isContentTemplate(context)) {
我认为在任何页面注入都是合理的，如果只想在某些路径下注入通过规则来就行，这取决于用户，Halo 的系统设置中也提供了全局注入的选项

2024-08-21 08:13 UTC, CaiHaosen commented on src/main/java/run/halo/injection/HtmlFooterProcessor.java
> +                    && isContentTemplate(context)) {
好的 我理解了

2024-08-22 03:31 UTC, guqing approved these changes
/lgtm

2024-08-22 03:32 UTC, merged