Implement UI with Basic CRUD Functionality
halo-sigs/plugin-injection pull request #6
Opened 2024-07-12 05:04 UTC by CaiHaosen

#### What type of PR is this?
/kind feature
#### What this PR does / why we need it:
此 PR 实现了代码注入插件的管理界面以及基本的增删改查，详情界面还未实现
#### Which issue(s) this PR fixes:
Fixes #4 
#### Does this PR introduce a user-facing change?
```release-note
None
```

2024-07-12 05:13 UTC, CaiHaosen commented
更改package.json中的依赖后再次提交

2024-07-12 09:57 UTC, ruibaby requested changes

2024-07-12 09:57 UTC, ruibaby commented on ui/package.json
>      "@halo-dev/ui-plugin-bundler-kit": "^2.12.0",
建议升级到 2.17.0，最新版本排除了请求（axios，@halo-dev/api-client）相关的依赖，可以降低捆绑包大小，其中 `@halo-dev/api-client` 中提供的 axiosInstance 也已经统一处理了异常逻辑，所以后续请求建议使用这个。

相关文档：https://docs.halo.run/developer-guide/plugin/api-reference/ui/api-request

2024-07-12 09:57 UTC, ruibaby commented on ui/package.json
> +    "vue-i18n": "9.13.1"
当前不建议在插件中为插件提供 i18n 支持，Halo 需要提供一个统一的解决方案。

2024-07-12 09:57 UTC, ruibaby commented on ui/src/index.ts
> +        path: "/HtmlInjection",
```suggestion
        path: "/html-injection",
```

2024-07-12 09:57 UTC, ruibaby commented on ui/src/types/index.ts
> +export interface Metadata {
引入 `@halo-dev/api-client` 之后可以在这个包中导入：

```ts
import type { Metadata } from "@halo-dev/api-client"
```

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +const { t } = useI18n();
同上，当前不建议做 i18n

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +  visible: boolean;
Modal 组件建议直接使用 v-if 去控制是否显示，没有必要在组件中维护太多状态，不需要显示的时候直接销毁。

可以参考：https://github.com/halo-dev/halo/blob/main/ui/console-src/modules/contents/posts/tags/components/TagEditingModal.vue

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +const http = axios.create({
同上，直接使用 `@halo-dev/api-client` 中的 axiosInstance

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +const resetFormData = () => {
同上，使用 v-if 控制显示之后就不需要处理这些状态了

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +);
同上，使用 v-if 控制显示之后就不需要处理这些状态了

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +  const requestData = {
建议添加类型约束。

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +            <FormKit
如果这个元素是一个数组，建议使用 list

文档：https://docs.halo.run/developer-guide/form-schema#list

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +        <VCard :body-class="['!p-0', '!overflow-visible']" class="mb-4">
建议所有表单元素放在一个 FormKit 即可，不需要给每一个表单项添加 VCard 组件。

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionList.vue
> +dayjs.extend(utc);
建议封装为一个 date util 文件。

2024-07-12 09:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionList.vue
> +const http = axios.create({
同上，使用 axiosInstance

2024-07-16 08:14 UTC, CaiHaosen commented on ui/src/views/HtmlInjectionAdd.vue
> +            <FormKit
Hi，谢谢你的建议！injectionPoint 是一个枚举类型，因此这里应该不需要使用 list

2024-07-16 08:20 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +            <FormKit
这里说的是 pageRules，我看应该是一个集合，https://github.com/halo-sigs/plugin-injection/blob/6cc79e28ded8d9bd6a04e5576debd66305219c79/src/main/java/run/halo/injection/HtmlInjection.java#L39

用 list 类型的输入框会让用户更好输入。

2024-07-17 07:32 UTC, guqing commented on ui/src/views/HtmlInjectionList.vue
> +                  <VButton :class="{ active: activeTab === 'All' }" @click="activeTab = 'All'">全部</VButton>
关于这里的操作按钮建议参考一下文章的写法,放到 `< VPageHeader>` 上，这块列表 header 的区域一般用做过滤条件，同时需要注意 button 的间距
<img width="437" alt="image" src="https://github.com/user-attachments/assets/9c5eb593-efd8-43c8-9161-9a4c44be55e9">

2024-07-17 09:04 UTC, guqing commented on ui/src/views/HtmlInjectionAdd.vue
> +              type="text"
这里的页面规则不应该是个 text ，规则应该允许输入多个，如 https://github.com/halo-sigs/plugin-injection/pull/6/files#r1678965872 所述的那样
<img width="595" alt="image" src="https://github.com/user-attachments/assets/4651a0ac-eb32-42d8-83e0-a0ec428fcc0b">

2024-07-19 03:18 UTC, guqing commented on ui/src/views/HtmlInjectionAdd.vue
> +  pageRules: new Set<string>(),
这里可以直接写成数组数组类型

2024-07-19 03:19 UTC, guqing commented on ui/src/types/index.ts
> +  pageRules: Set<string>;
这里可以直接写成数组类型

2024-07-19 03:24 UTC, guqing commented on ui/src/index.ts
>        parentName: "Root",
这里改为 ToolsRoot 然后移除掉 meta.menu.group 以将 代码注入放到 Halo 默认提供的**工具**菜单下作为子菜单

2024-07-19 03:27 UTC, guqing commented on ui/src/views/HtmlInjectionList.vue
> +               共{{ filteredTotal }} 项数据
```suggestion
               共 {{ filteredTotal }} 项数据
```

2024-07-19 03:37 UTC, ruibaby requested changes
这里有两个关于表单提交的建议。

具体可参考：[Submitting via XHR/Fetch request](https://formkit.com/inputs/form#submitting-via-xhrfetch-request)

2024-07-19 03:37 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +              v-model="formData.name"
建议移除表单项的 v-model 双向绑定，对于表单的最佳实践是通过定义 name 属性，然后在 `@submit` 事件中拿到表单数据。

2024-07-19 03:37 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +        <VButton type="secondary" @click="submitForm">
提交表单时，直接调用 submitForm 是不会经过表单验证的，建议使用 `$formkit.submit('html-injection-form')` 触发表单提交事件。

2024-07-19 03:43 UTC, ruibaby requested changes

2024-07-19 03:43 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +          <VTabbar
这里推荐将代码编辑界面和其他设置放在一起，使用选项卡将一个表单分为两个，这样使用体验可能不会太好。

如果考虑到代码编辑表单项太小，不方便编辑内容的话，可以等待 https://github.com/halo-dev/halo/issues/6308 实现。

2024-07-24 06:53 UTC, CaiHaosen commented on ui/src/views/HtmlInjectionAdd.vue
> +        <VButton type="secondary" @click="submitForm">
Hi! @ruibaby 谢谢提供的建议和参考，我已经通过 `$formkit.submit`实现了表单的提交和验证，但总有提示 `Vue: Property $formkit does not exist on type `。我参考了 [plugin-links-LinkEditingModal.vue](https://github.com/halo-sigs/plugin-links/blob/e73ef060b53371f78bd94ab16f3b3ffd413ce11d/console/src/components/LinkEditingModal.vue) 以及其 package.json ，将 build 设置为 vite build 以避免类型检查。虽然依然会有该提示，但项目可以成功调用 $formkit.submit 方法经过表单验证。不确定这种方式是否可行？

2024-07-24 06:57 UTC, ruibaby commented on ui/src/views/HtmlInjectionAdd.vue
> +        <VButton type="secondary" @click="submitForm">
> Hi! @ruibaby 谢谢提供的建议和参考，我已经通过 `$formkit.submit`实现了表单的提交和验证，但总有提示 `Vue: Property $formkit does not exist on type `。我参考了 [plugin-links-LinkEditingModal.vue](https://github.com/halo-sigs/plugin-links/blob/e73ef060b53371f78bd94ab16f3b3ffd413ce11d/console/src/components/LinkEditingModal.vue) 以及其 package.json ，将 build 设置为 vite build 以避免类型检查。虽然依然会有该提示，但项目可以成功调用 $formkit.submit 方法经过表单验证。不确定这种方式是否可行？

可以使用是因为 FormKit 已经在 Halo 核心全局注册，但因为在插件工程里没有 FormKit 类型，所以提示 ts 异常，暂时可以在按钮上方添加 `<!-- @vue-ignore -->` 注释以忽略这个问题。

2024-07-24 07:13 UTC, guqing commented on ui/package.json
> +    "canvas-confetti": "^1.9.3",
这个 canvas-confetti 应该已经没用了，可以去掉，它是在脚手架中放烟花用的,此建议不影响 PR 合并

2024-07-25 03:50 UTC, guqing approved these changes
/lgtm

2024-07-25 03:51 UTC, merged